---------------------------------------------------------------------------------------------------------------------
-- Insert table scripts for Asset / Inventory related information (MODEL, MANUFACTURER, SUBCONTRACTOR, CLIENT, ASSET)
---------------------------------------------------------------------------------------------------------------------

-- Insert script for Table: MODEL
INSERT INTO ATM_ICBC.MODEL (MODEL, RELEASED, MEMORY, PROCESSOR)
SELECT DISTINCT INV.WINCOR_MODEL, '01/01/1900', NULL, NULL 
  FROM BASE_ICBC.INVENTORY AS INV;

-- Insert script for Table: MANUFACTURER
INSERT INTO ATM_ICBC.MANUFACTURER (MANUFACTURER, COMMENT)
SELECT DISTINCT INV.MANUFACTURER, NULL
  FROM BASE_ICBC.INVENTORY AS INV;

-- Insert script for Table: SUBCONTRACTOR
INSERT INTO ATM_ICBC.SUBCONTRACTOR (SUBCONTRACTOR, COMMENT)
SELECT DISTINCT 'IBM', NULL
  FROM BASE_ICBC.INVENTORY AS INV;

-- Insert script for Table: CLIENT
INSERT INTO ATM_ICBC.CLIENT (CLIENT, CONTRACT, LOCATION, REQUIREMENTS)
VALUES ('ICBC Argentina', 'BR583', 'Argentina', NULL);

-- Insert script for Table: ASSET
INSERT INTO ATM_ICBC.ASSET (IDCLIENT, IDMODEL, IDMANUFACTURER, IDSUBCONTRACTOR, IDORIGINAL, 
                            IDORIGINALIBM, MODULE_DEPOSITOR, MODULE_DISPENSER, MODULE_RECYCLING, 
                            MODULE_CCDM, INSTALLATION_OUTSIDE, LOCATION, SCHEDULE, INSTALLED, 
                            DEINSTALLED, SNAPSHOT, SOFTWARE)
SELECT (SELECT C.IDCLIENT
          FROM ATM_ICBC.CLIENT AS C
         WHERE C.CLIENT = 'ICBC Argentina'), 
       (SELECT M.IDMODEL
          FROM ATM_ICBC.MODEL AS M
         WHERE M.MODEL = INV.WINCOR_MODEL), 
       (SELECT MFR.IDMANUFACTURER
          FROM ATM_ICBC.MANUFACTURER AS MFR
         WHERE MFR.MANUFACTURER = INV.MANUFACTURER), 
       (SELECT S.IDSUBCONTRACTOR
          FROM ATM_ICBC.SUBCONTRACTOR AS S
         WHERE S.SUBCONTRACTOR = 'IBM'), 
       INV.UNIQUE_ATM_ID, 
       INV.IBM_SERIAL, 
       (SUBSTR(INV.ENVELOPE_MODULE, 1, 1)), 
       (SUBSTR(INV.CASH_DISPENSER, 1, 1)),
       (SUBSTR(INV.RECYLCLING_MODULE, 1, 1)), 
       (SUBSTR(INV.CCDM, 1, 1)), 
       'N', 
       (SELECT LOC.LATITUDE CONCAT ',' CONCAT LOC.LONGITUDE
          FROM NIKIFOR.ICBC_LOCATION AS LOC
         WHERE LOC.IBM_SERIAL = INV.IBM_SERIAL), 
       NULL, 
       INV.INSTALLED_DATE, 
       INV.DEINSTALLATION_DATE, 
       ('01-23-2018'), 
       NULL
  FROM BASE_ICBC.INVENTORY AS INV;
  
